### ISSUE TITLE
How to use XDebug trigger mode in VSCode "Launch currently open script"?

### ISSUE THREAD

**Issue by mwittmann** [xdebug/vscode-php-debug#699]
Does anyone know how to use trigger mode? 

```
xdebug.start_with_request=trigger
```

I can't trigger it from the command line or the browser. 

When set to `yes` it works.

In order to avoid xdebug from complaining on each request when xdebug client is stopped, this should be set to trigger or even omitted since `xdebug.mode = debug` sets this to trigger.

_Originally posted by @mabasic in https://github.com/xdebug/vscode-php-debug/issues/411#issuecomment-749255950_

**Comment by mwittmann** [comment]
Although breakpoints were working for me in regular PHP website code running under Apache, I could not get breakpoints to work for VSCode's "Launch currently open script" debugger configuration with the Xdebug settings `xdebug.start_with_request=trigger` and `xdebug.trigger_value=VSCODE`.

After research, trial and error, I discovered that to get breakpoints to work in this case, I simply had to set the correct environment variables in an `"env"` section in `launch.json` settings . My `launch.json` contains:

```
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9003,
            "pathMappings": {
                "/srv/www/mywebsiteroot": "${workspaceRoot}" 
            },
            "stopOnEntry": true,
            //"log": true,
            "env": {
                "XDEBUG_MODE": "debug",
                "XDEBUG_TRIGGER": "VSCODE"
            }
        },
```
The `"stopOnEntry": true` setting is not really needed. I changed it to `false` once I verified my breakpoints were working.

Hope this helps someone else!

**Comment by zobo** [comment]
Hi @mwittmann!

The documentation for [start_with_request](https://xdebug.org/docs/step_debug#start_with_request) and [trigger_value](https://xdebug.org/docs/all_settings#trigger_value).

The `trigger_value` controls if and what value the trigger (env or cookie XDEBUG_TRIGGER) has to be. If you do not set it, than it doesn't matter. From docs:
>Normally, Xdebug does not look at which value is actually used. If this setting is set to a non-empty string, then Xdebug will only trigger if the value matches the value of this setting.

So, unless you are trying to protect the trigger from somebody else, you could just drop it.

However I see other issues here:

1. Why do you have path mappings? If you run the code with VSCode, then you are already looking at the files the same way as php executable is. It probably wont interfere, but it could.
2. Your "Launch script" configuration snippet seems outdated. If you ask VSCode to create the `launch.json` file or add a configuration snippet for "Launch currently open script" you should get something like this:
```
		{
			"name": "Launch currently open script",
			"type": "php",
			"request": "launch",
			"program": "${file}",
			"cwd": "${fileDirname}",
			"port": 0,
			"runtimeArgs": [
				"-dxdebug.start_with_request=yes"
			],
			"env": {
				"XDEBUG_MODE": "debug,develop",
				"XDEBUG_CONFIG": "client_port=${port}"
			}
		},
```
What happens here is that when executing the php binary, VSCode will also pass the `-d xdebug.start_with_request=yes` parameter, causing debugging to start right away. Env XDEBUG_MODE is set like in your example, but also the `client_port` is overridden. See the `port` setting, it is set to 0, that means a random port will be allocated.
This are all just small optimizations to make debugging work better and more effortless. Again, path mappings should not be needed, as you are looking at the same code you are running - compared to a webserver case, where somebody could be using SMB to access the files, or Docker or other combinations...

For triggering debugging in you browser, I highly recommend one of the `Xdebug helper` extensions. There the default `xdebug.start_with_request=trigger` makes most sense.

**Comment by zobo** [comment]
Please reopen if you need anything further.

**Comment by JackLeEmmerdeur** [comment]
Thanks to the answers on this thread and monkey-patching the 2 config files, debug-sessions now work from the vscode-extension *PHPDebug 6.816.386* into a docker container running xdebug from docker-image *php:8.0.20RC1-zts-alpine3.16*.

The debug-session is only initiated when a breakpoint is triggered.

---
**Configuration for xdebug Inside the container**
**The mapping from a projects sub-folder is shown further down within the docker-compose.yml** 
**/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini**
```
zend_extension=xdebug

[xdebug]
xdebug.mode = debug
xdebug.discover_client_host=true
xdebug.client_port = 9003
xdebug.start_with_request=yes
xdebug.log="/tmp/xdebug.log"
xdebug.idekey = VSCODE
```
---
**Overwrite the php error-reporting-level**
**Also mapping is made in docker-compose.yml**
**/usr/local/etc/php/conf.d/error_reporting.ini**
```
error_reporting=E_ALL
```
---
**Excerpt from local docker-compose.json**
```
  laravel:
    container_name: laravel
    build:
       context: .
       dockerfile: Dockerfile
    networks:
      backend:
        ipv4_address: 172.16.238.3
    expose:
      - 80
    volumes:
      - ./:/app/public/
      - ./docker/php-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - exclude:/app/public/node_modules
  networks:
    backend:
      driver: bridge
      enable_ipv6: true
      ipam:
        driver: default
        config:
          - subnet: 172.16.238.0/24
            gateway: 172.16.238.1
          - subnet: 2001:3984:3989::/64
            gateway: 2001:3984:3989::1
```
---
**Local VSCode launch configuration**
**/project/.vscode/launch.json**
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for Xdebug",
			"type": "php",
			"request": "launch",
			"pathMappings": {
				// The folder "/app/public/" contains a laravel-installation
				"/app/public/": "${workspaceFolder}"
			},
			"env": {
				"XDEBUG_MODE": "debug,develop",
				"XDEBUG_CONFIG": "client_port=${port}"
			},
			"runtimeArgs": [
				"-dxdebug.start_with_request=yes"
			]
		},
	]
}
```
