### ISSUE TITLE
`Time-out connecting to debugging client` after it was working correctly

### ISSUE THREAD

**Issue by goncalovf** [xdebug/vscode-php-debug#987]
## Issue description

I'm running a project with Docker from WSL2 in a Windows machine. I was using Xdebug with the PHP Debug extension successfully, but recently it stopped working with the following error:

```
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: 172.18.238.16:9007 (through xdebug.client_host/xdebug.client_port).
```

I believe it stopped working after I upgraded Docker Desktop, perhaps among other upgrades. I currently use the Cursor IDE, but this issue was happening on VS Code as well.

## Project configuration

I start my project running `sh -c 'docker-compose -f compose.common.yml -f compose.ff.yml up --detach'` on WSL2 Ubuntu.

```yml
# compose.common.yml

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  wp_base:
    build: ./docker/wp
    depends_on:
      - db
    restart: on-failure
    user: www-data
    environment:
      # For wordpress image
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: "include( 'extra-config.php' );"
      # Our own environment variables
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:-host.docker.internal}

# and a few other containers...
```

```yml
# compose.ff.yml

services:
    wp_connect_ff:
      extends:
        file: compose.common.yml
        service: wp_base
      container_name: connect.ff.local
      ports:
        - "9097:80"
      volumes:
        # Common
        - ./plugins:/var/www/html/wp-content/plugins
        - ./themes:/var/www/html/wp-content/themes
        # and a few other volumes...
      environment:
        # For wordpress image
        WORDPRESS_DB_NAME: ffconnect
        # For nginx-proxy image
        VIRTUAL_HOST: connect.ff.local
        # Our own environment variables
        XDEBUG_CLIENT_PORT: 9007
      extra_hosts:
        - 'connect.ff.local:127.0.0.1'
```

```.env
# .env

XDEBUG_CLIENT_HOST=172.18.238.16
```

I got the `172.18.238.16` IP from running `ifconfig` in my Ubuntu WSL2.

![Image](https://github.com/user-attachments/assets/33a16bd8-62ba-4e50-a2fe-3ad18184038f)

```Dockerfile
# docker/wp/Dockefile

FROM wordpress:6.6.2-php8.2-apache

COPY --from=composer /usr/bin/composer /usr/bin/composer

# Development tooling dependencies
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		bash less default-mysql-client git zip unzip \
		curl pv \
		msmtp libz-dev libmemcached-dev \
	&& rm -rf /var/lib/apt/lists/* \
    && pecl install xdebug memcache \
    && docker-php-ext-enable xdebug memcache;

# Include our custom config for PHP and Xdebug.
COPY php.ini /usr/local/etc/php/conf.d/

# Install Composer dependencies and add vendor/bin to the path.
COPY composer.json .
RUN composer install
ENV PATH /var/www/html/vendor/bin:$PATH

WORKDIR /var/www/html/

# Register a directory to be used as a volume.
RUN mkdir -p /volume.d
VOLUME /volume.d
```

```ini
# docker/wp/php.ini

memory_limit = -1
upload_max_filesize = 1G
post_max_size = 1G

# Forward mail to the MailHog container. Use SMTPSERVER and EMAIL
# environment variables to specify --host and --from values.
sendmail_path = "/usr/bin/msmtp --port=1025 --read-recipients"

[xdebug]
# For Xdebug 2
xdebug.remote_autostart=1
xdebug.remote_connect_back = 1
xdebug.remote_enable = 1
xdebug.remote_host = ${XDEBUG_CLIENT_HOST}
xdebug.remote_port = ${XDEBUG_CLIENT_PORT}

# For Xdebug 3
xdebug.client_host = ${XDEBUG_CLIENT_HOST}
xdebug.client_port = ${XDEBUG_CLIENT_PORT}
xdebug.discover_client_host = 0
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.log = /tmp/xdebug.log

[opcache]
opcache.enable = 1
opcache.validate_timestamps = 1

```

My `.vscode/launch.json` file:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "connect.ff.local Xdebug",
			"type": "php",
			"request": "launch",
			"port": 9007,
			"pathMappings": {
				"/var/www/html/wp-admin": "${workspaceFolder}/wordpress/wp-admin",
				"/var/www/html/wp-content/plugins": "${workspaceFolder}/plugins",
				"/var/www/html/wp-content/themes": "${workspaceFolder}/themes",
				"/var/www/html/wp-includes": "${workspaceFolder}/wordpress/wp-includes"
			}
		}
	]
}

```

## System details

Info I get in Cursor IDE's `Help > About` menu:

```
Version: 0.45.10
VSCode Version: 1.96.2
Commit: 15746f716efa868ebac16b1675bad2714d6c27d0
Date: 2025-02-05T06:20:28.304Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

Running `lsb_release -a` on WSL2 Ubuntu:
```sh
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Windows 10 Pro 64-bit.

Docker Desktop version: 4.36.0 (175267).

I ran the following on PowerShell, as [suggested here](https://github.com/microsoft/WSL/issues/4585#issuecomment-610061194):

```PowerShell
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow
```

## Output of `xdebug_info()`

![Image](https://github.com/user-attachments/assets/9b23777c-af86-4451-b8d6-aec6a0abf468)

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/789fde80-db62-4886-b0aa-715756b28283" />

## What I've tried

Among other things, I tried:
* Replacing the value of `XDEBUG_CLIENT_HOST` in `.env` with:
    * `host.docker.internal`, placing `'host.docker.internal:host-gateway'` as an `extra_hosts` in the `wp_connect_ff` service in `compose.ff.yml`.
    * IPv4 addresses from Window's `ipconfig` command (under `Ethernet adapter vEthernet (WSL)` and `Wireless LAN adapter Wi-Fi`).
* Adding `"hostname": "localhost"` and `"hostname": "0.0.0.0"` in the configuration in `.vscode/launch.json`.
